"use client";

import { useCallback, useEffect, useState } from "react";
import { Edit3, Plus, Trash2, X } from "lucide-react";
import { createBlogCategory, createBlogTag, deleteBlogCategory, deleteBlogTag, getBlogCategories, getBlogTags, updateBlogCategory, updateBlogTag, uploadBlogImage, type BlogTaxonomy } from "@/lib/blog";

type Kind = "category" | "tag";
function slugify(value: string) { return value.toLowerCase().trim().replace(/&/g," and ").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,""); }

export default function BlogTaxonomyManager({ kind }: { kind: Kind }) {
  const isCategory = kind === "category";
  const [items, setItems] = useState<BlogTaxonomy[]>([]);
  const [name, setName] = useState(""); const [slug, setSlug] = useState(""); const [description, setDescription] = useState("");
  const [image, setImage] = useState<any>({ url:"", publicId:"" }); const [isActive, setIsActive] = useState(true);
  const [editingId, setEditingId] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");

  const load = useCallback(async () => { try { setLoading(true); setError(""); setItems(isCategory ? await getBlogCategories() : await getBlogTags()); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load data."); } finally { setLoading(false); } }, [isCategory]);
  useEffect(() => { void load(); }, [load]);

  function clear() { setName(""); setSlug(""); setDescription(""); setImage({url:"",publicId:""}); setIsActive(true); setEditingId(""); }
  function edit(item: BlogTaxonomy) { setEditingId(item._id); setName(item.name); setSlug(item.slug); setDescription(item.description || ""); setImage(item.image || {url:"",publicId:""}); setIsActive(item.isActive !== false); }
  async function save() {
    if (!name.trim()) return setError(`${isCategory ? "Category" : "Tag"} name is required.`);
    try { setSaving(true); setError(""); const body:any = { name:name.trim(), slug:slug.trim() || slugify(name) }; if (isCategory) Object.assign(body,{description,image,isActive}); if (editingId) { if (isCategory) await updateBlogCategory(editingId,body); else await updateBlogTag(editingId,body); } else { if (isCategory) await createBlogCategory(body); else await createBlogTag(body); } clear(); await load(); } catch(e) { setError(e instanceof Error?e.message:"Unable to save."); } finally { setSaving(false); }
  }
  async function remove(item: BlogTaxonomy) { if (!confirm(`Delete \"${item.name}\"?`)) return; try { if(isCategory) await deleteBlogCategory(item._id); else await deleteBlogTag(item._id); if(editingId===item._id) clear(); await load(); } catch(e){ alert(e instanceof Error?e.message:"Unable to delete."); } }
  async function upload(file: File) { try { setSaving(true); const result=await uploadBlogImage(file, `blog-category-${slugify(name)||"image"}`); setImage({url:result.url,publicId:result.publicId,width:result.width,height:result.height}); } catch(e){ setError(e instanceof Error?e.message:"Upload failed."); } finally { setSaving(false); } }

  return <div className="min-h-full bg-[#F8F5F2] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1250px]"><div className="mb-6"><p className="text-[9px] font-semibold uppercase tracking-[0.22em] text-[#A51D45]">Blog Management</p><h1 className="mt-2 text-3xl font-semibold">Blog {isCategory?"Categories":"Tags"}</h1></div><div className="grid gap-5 lg:grid-cols-[390px_1fr]">
    <section className="h-fit rounded-[22px] border border-[#211A18]/10 bg-white p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-semibold">{editingId?"Edit":"Add"} {isCategory?"Category":"Tag"}</h2>{editingId&&<button onClick={clear} className="flex h-8 w-8 items-center justify-center rounded-lg border"><X size={14}/></button>}</div>{error&&<div className="mb-3 rounded-lg bg-red-50 p-3 text-[10px] text-red-600">{error}</div>}<div className="space-y-3"><label><span className="mb-1 block text-[8px] font-semibold uppercase text-[#211A18]/40">Name</span><input className="field" value={name} onChange={(e)=>{setName(e.target.value); if(!editingId)setSlug(slugify(e.target.value));}}/></label><label><span className="mb-1 block text-[8px] font-semibold uppercase text-[#211A18]/40">Slug</span><input className="field" value={slug} onChange={(e)=>setSlug(slugify(e.target.value))}/></label>{isCategory&&<><label><span className="mb-1 block text-[8px] font-semibold uppercase text-[#211A18]/40">Description</span><textarea rows={4} className="textarea" value={description} onChange={(e)=>setDescription(e.target.value)}/></label><div><span className="mb-1 block text-[8px] font-semibold uppercase text-[#211A18]/40">Image</span>{image.url&&<img src={image.url} alt={name} className="mb-2 h-28 w-full rounded-xl object-cover"/>}<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={(e)=>e.target.files?.[0]&&void upload(e.target.files[0])} className="block w-full text-[9px]"/></div><label className="flex items-center gap-2 text-[10px] font-semibold"><input type="checkbox" checked={isActive} onChange={(e)=>setIsActive(e.target.checked)} className="accent-[#A51D45]"/>Active</label></>}</div><button disabled={saving} onClick={()=>void save()} className="mt-5 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#A51D45] text-[10px] font-semibold text-white disabled:opacity-50"><Plus size={14}/>{saving?"Saving...":editingId?"Update":"Add"}</button></section>
    <section className="overflow-hidden rounded-[22px] border border-[#211A18]/10 bg-white"><div className="border-b border-[#211A18]/10 px-5 py-4 text-[11px] font-semibold">{items.length} {isCategory?"Categories":"Tags"}</div>{loading?<div className="p-12 text-center text-sm text-[#211A18]/45">Loading...</div>:items.length===0?<div className="p-12 text-center text-sm text-[#211A18]/45">No items found.</div>:<div className="divide-y divide-[#211A18]/7">{items.map((item)=><div key={item._id} className="flex items-center gap-4 px-5 py-4">{isCategory&&<div className="h-11 w-14 overflow-hidden rounded-lg bg-[#F4EFEC]">{item.image?.url&&<img src={item.image.url} alt={item.name} className="h-full w-full object-cover"/>}</div>}<div className="min-w-0 flex-1"><div className="text-[11px] font-semibold">{item.name}</div><div className="mt-1 text-[9px] text-[#211A18]/40">/{item.slug}{isCategory&&item.isActive===false?" • Inactive":""}</div></div><button onClick={()=>edit(item)} className="flex h-8 w-8 items-center justify-center rounded-lg border border-[#211A18]/10"><Edit3 size={13}/></button><button onClick={()=>void remove(item)} className="flex h-8 w-8 items-center justify-center rounded-lg border border-red-100 text-red-600"><Trash2 size={13}/></button></div>)}</div>}</section>
  </div></div></div>;
}
