"use client";

import Link from "next/link";
import { useCallback, useEffect, useState, type ReactNode } from "react";
import { ArrowLeft, BarChart3, ChevronDown, Download, FileSpreadsheet, FileText, Loader2, RefreshCcw, TrendingDown, TrendingUp } from "lucide-react";

const API_URL = (process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000").replace(/\/$/, "");
type Period = "1_month" | "3_months" | "6_months" | "1_year" | "all";
type Report = any;
const periods: Array<[Period, string]> = [["1_month","1 Month"],["3_months","3 Months"],["6_months","6 Months"],["1_year","1 Year"],["all","All"]];

function money(value: unknown) { const n = Number(value || 0); return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 }).format(Number.isFinite(n) ? n : 0); }
function number(value: unknown) { const n=Number(value||0); return Number.isFinite(n)?n.toLocaleString("en-IN"):"0"; }
function pct(value: unknown) { const n=Number(value); return Number.isFinite(n)?`${n>=0?"+":""}${n.toFixed(2)}%`:"—"; }
async function readJson(r: Response) { try { return await r.json(); } catch { return {}; } }

export default function OrderReportsPage(){
  const [period,setPeriod]=useState<Period>("1_month"); const [report,setReport]=useState<Report|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [exportOpen,setExportOpen]=useState(false); const [exporting,setExporting]=useState("");
  const load=useCallback(async()=>{try{setLoading(true);setError("");const r=await fetch(`${API_URL}/api/admin/orders/reports?period=${period}`,{credentials:"include",cache:"no-store"});const d=await readJson(r);if(!r.ok)throw new Error(d?.message||"Unable to load reports.");setReport(d.report||null);}catch(e){setReport(null);setError(e instanceof Error?e.message:"Unable to load reports.");}finally{setLoading(false)}},[period]);
  useEffect(()=>{void load()},[load]);
  async function exportReport(format:string){try{setExporting(format);setExportOpen(false);setError("");const r=await fetch(`${API_URL}/api/admin/orders/reports/export?period=${period}&format=${format}`,{credentials:"include"});if(!r.ok){const d=await readJson(r);throw new Error(d?.message||"Unable to generate report.");}const blob=await r.blob();const disposition=r.headers.get("content-disposition")||"";const name=disposition.match(/filename="?([^";]+)"?/i)?.[1]||`hivrasoft-orders-report.${format}`;const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}catch(e){setError(e instanceof Error?e.message:"Unable to generate report. Please try again.");}finally{setExporting("")}}
  const summary=report?.summary||{};
  return <section className="mx-auto w-full max-w-[1600px] pb-12">
    <div className="rounded-[26px] bg-[#211A18] p-6 text-white md:p-8">
      <div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><Link href="/admin/orders" className="inline-flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.16em] text-white/55 hover:text-white"><ArrowLeft size={14}/> Orders</Link><p className="mt-5 text-[9px] font-semibold uppercase tracking-[.24em] text-[#E7AE72]">Analytics</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.035em]">Order & Sales Reports</h1><p className="mt-2 max-w-2xl text-xs leading-5 text-white/55">Live reporting from HivraSoft order data. The active period controls every card, chart, state summary and export.</p></div>
      <div className="relative"><button disabled={Boolean(exporting)} onClick={()=>setExportOpen(v=>!v)} className="inline-flex h-11 items-center gap-2 rounded-xl bg-white px-4 text-[10px] font-semibold uppercase tracking-wide text-[#211A18] disabled:opacity-60">{exporting?<Loader2 size={14} className="animate-spin"/>:<Download size={14}/>} {exporting?"Generating report...":"Export Report"}<ChevronDown size={13}/></button>{exportOpen&&<div className="absolute right-0 z-30 mt-2 w-52 rounded-2xl border border-white/10 bg-white p-2 text-[#211A18] shadow-2xl">{[["pdf","PDF",FileText],["xlsx","Excel (.xlsx)",FileSpreadsheet],["csv","CSV",FileSpreadsheet],["xml","XML",FileText]].map(([format,label,Icon]:any)=><button key={format} onClick={()=>void exportReport(format)} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-[11px] font-semibold hover:bg-[#FAF8F6]"><Icon size={15} className="text-[#8C1839]"/>{label}</button>)}</div>}</div></div>
    </div>

    <div className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-[20px] border border-[#211A18]/10 bg-white p-3"><div className="flex flex-wrap gap-2">{periods.map(([value,label])=><button key={value} onClick={()=>setPeriod(value)} className={`h-10 rounded-xl px-4 text-[10px] font-semibold transition ${period===value?"bg-[#8C1839] text-white":"bg-[#FAF8F6] text-[#211A18]/60 hover:text-[#8C1839]"}`}>{label}</button>)}</div><button onClick={()=>void load()} className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#211A18]/10 px-4 text-[10px] font-semibold text-[#211A18]/60"><RefreshCcw size={13}/> Refresh</button></div>
    {error&&<div className="mt-4 flex items-center justify-between rounded-xl border border-red-200 bg-red-50 p-4 text-xs text-red-700"><span>{error}</span><button onClick={()=>void load()} className="font-semibold">Retry</button></div>}
    {loading?<Loading/>:!report?<Empty/>:<>
      <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Total Sales" value={money(summary.totalSales)} change={summary.change?.totalSales}/><Metric title="Orders Completed" value={number(summary.completedOrders)} change={summary.change?.completedOrders}/><Metric title="Total Orders" value={number(summary.totalOrders)} change={summary.change?.totalOrders}/><Metric title="Cancelled Orders" value={number(summary.cancelledOrders)} change={summary.change?.cancelledOrders}/></div>
      <div className="mt-5 grid gap-5 xl:grid-cols-[1.55fr_.85fr]"><Card title="Total Sales Over Time" subtitle="Current period with previous-period comparison"><LineChart data={report.salesSeries||[]}/></Card><Card title="Invoice Statistic" subtitle={`${number(summary.totalOrders)} total orders`}><Donut rows={report.statusStats||[]} total={Number(summary.totalOrders||0)}/></Card></div>
      <div className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_.95fr]"><Card title="Number of Orders" subtitle="Orders grouped by the active report period"><BarChart data={report.orderSeries||[]}/></Card><Card title="Top Selling State" subtitle="Share of valid orders"><div className="max-h-[330px] space-y-4 overflow-y-auto pr-2">{(report.stateSummary||[]).length?(report.stateSummary||[]).map((row:any)=><div key={`${row.state}-${row.stateCode}`}><div className="mb-1.5 flex justify-between text-[10px]"><span className="font-semibold text-[#211A18]">{row.state||"Unknown"}</span><span className="text-[#211A18]/50">{Number(row.percentage||0).toFixed(2)}% · {number(row.orders)} orders</span></div><div className="h-2 overflow-hidden rounded-full bg-[#F1ECE8]"><div className="h-full rounded-full bg-[#8C1839]" style={{width:`${Math.min(100,Number(row.percentage||0))}%`}}/></div></div>):<NoData/>}</div></Card></div>
      <div className="mt-5 grid gap-5 xl:grid-cols-[1fr_1fr]"><Card title="Sales Breakdown" subtitle="Calculated from the same filtered order set"><div className="divide-y divide-[#211A18]/7">{[["Gross Sales",summary.grossSales],["Discounts",-Number(summary.discounts||0)],["Refund",-Number(summary.refunds||0)],["Net Sales",summary.netSales],["Shipping Charges",summary.shipping],["Taxes",summary.taxes],["Cancelled",-Number(summary.cancelledValue||0)],["Total Sales",summary.totalSales]].map(([label,value],i)=><div key={String(label)} className={`flex items-center justify-between py-3 text-[11px] ${i===7?"font-bold text-[#8C1839]":""}`}><span>{label}</span><span>{money(value)}</span></div>)}</div></Card><Card title="State-wise Summary" subtitle="Unique orders and actual item quantity"><div className="max-h-[360px] overflow-auto"><table className="w-full min-w-[620px] text-left text-[10px]"><thead className="sticky top-0 bg-[#FAF8F6] text-[8px] uppercase tracking-wide text-[#211A18]/45"><tr><th className="px-3 py-3">State</th><th className="px-3 py-3">Orders</th><th className="px-3 py-3">Qty</th><th className="px-3 py-3">Subtotal</th><th className="px-3 py-3">Tax</th><th className="px-3 py-3">Total</th></tr></thead><tbody>{(report.stateSummary||[]).map((row:any)=><tr key={`${row.state}-row`} className="border-t border-[#211A18]/7"><td className="px-3 py-3 font-semibold">{row.state} <span className="text-[#211A18]/35">{row.stateCode}</span></td><td className="px-3 py-3">{number(row.orders)}</td><td className="px-3 py-3">{number(row.quantity)}</td><td className="px-3 py-3">{money(row.subtotal)}</td><td className="px-3 py-3">{money(row.tax)}</td><td className="px-3 py-3 font-semibold">{money(row.total)}</td></tr>)}</tbody></table>{!(report.stateSummary||[]).length&&<NoData/>}</div></Card></div>
    </>}
  </section>
}

function Metric({title,value,change}:{title:string;value:string;change:number|null|undefined}){const up=typeof change==="number"&&change>=0;return <div className="rounded-[22px] border border-[#211A18]/10 bg-white p-5 shadow-[0_12px_36px_rgba(33,26,24,.04)]"><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-[#211A18]/40">{title}</p><p className="mt-3 text-2xl font-semibold tracking-[-.03em] text-[#211A18]">{value}</p><div className={`mt-3 flex items-center gap-1 text-[10px] font-semibold ${change==null?"text-[#211A18]/35":up?"text-emerald-600":"text-red-600"}`}>{change==null?null:up?<TrendingUp size={13}/>:<TrendingDown size={13}/>} {pct(change)} <span className="font-normal text-[#211A18]/35">vs previous period</span></div></div>}
function Card({title,subtitle,children}:{title:string;subtitle:string;children:ReactNode}){return <section className="rounded-[22px] border border-[#211A18]/10 bg-white p-5 md:p-6"><div className="mb-5"><h2 className="text-[15px] font-semibold text-[#211A18]">{title}</h2><p className="mt-1 text-[9px] text-[#211A18]/40">{subtitle}</p></div>{children}</section>}
function Loading(){return <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[0,1,2,3].map(i=><div key={i} className="h-32 animate-pulse rounded-[22px] bg-[#EEE8E4]"/>)}</div>}
function Empty(){return <div className="mt-5 rounded-[22px] border border-[#211A18]/10 bg-white py-16 text-center"><BarChart3 className="mx-auto text-[#8C1839]"/><p className="mt-3 text-sm font-semibold">No order data available for this period.</p></div>}
function NoData(){return <p className="py-10 text-center text-[10px] text-[#211A18]/40">No order data available for this period.</p>}

function LineChart({data}:{data:any[]}){const values=data.map(d=>Number(d.value||0));const prev=data.map(d=>Number(d.previous||0));const max=Math.max(1,...values,...prev);const width=760,height=260,pad=28;const points=(arr:number[])=>arr.map((v,i)=>`${pad+(i*Math.max(1,width-pad*2))/(Math.max(1,arr.length-1))},${height-pad-(v/max)*(height-pad*2)}`).join(" ");if(!data.length)return <NoData/>;return <div className="overflow-hidden"><svg viewBox={`0 0 ${width} ${height}`} className="h-[260px] w-full"><line x1={pad} y1={height-pad} x2={width-pad} y2={height-pad} stroke="rgba(33,26,24,.14)"/><polyline fill="none" stroke="#8C1839" strokeWidth="3" points={points(values)}/>{prev.some(v=>v>0)&&<polyline fill="none" stroke="#B89C91" strokeWidth="2" strokeDasharray="7 6" points={points(prev)}/>} {values.map((v,i)=>{const x=pad+(i*Math.max(1,width-pad*2))/(Math.max(1,values.length-1));const y=height-pad-(v/max)*(height-pad*2);return <g key={i}><circle cx={x} cy={y} r="3.5" fill="#8C1839"><title>{data[i].label}: {money(v)}</title></circle>{(i===0||i===values.length-1||i%Math.max(1,Math.ceil(values.length/6))===0)&&<text x={x} y={height-7} textAnchor="middle" fontSize="9" fill="rgba(33,26,24,.5)">{data[i].label}</text>}</g>})}</svg><div className="mt-1 flex gap-4 text-[9px] text-[#211A18]/45"><span>— Current period</span><span>-- Previous period</span></div></div>}
function BarChart({data}:{data:any[]}){if(!data.length)return <NoData/>;const max=Math.max(1,...data.map(d=>Number(d.value||0)));return <div className="flex h-[270px] items-end gap-1 overflow-hidden border-b border-[#211A18]/10 px-1 pb-7">{data.map((d,i)=><div key={d.key||i} className="group relative flex h-full min-w-0 flex-1 items-end"><div className="w-full rounded-t bg-[#8C1839]/80 transition group-hover:bg-[#8C1839]" style={{height:`${Math.max(2,(Number(d.value||0)/max)*92)}%`}} title={`${d.label}: ${d.value} orders`}/>{(i===0||i===data.length-1||i%Math.max(1,Math.ceil(data.length/7))===0)&&<span className="absolute -bottom-5 left-1/2 -translate-x-1/2 whitespace-nowrap text-[8px] text-[#211A18]/45">{d.label}</span>}</div>)}</div>}
function Donut({rows,total}:{rows:any[];total:number}){const colors=["#8C1839","#2E8B72","#C78A45","#B7AAA4"];let acc=0;const stops=rows.map((row,i)=>{const start=acc;acc+=Number(row.percentage||0);return `${colors[i%colors.length]} ${start}% ${acc}%`}).join(",");return <div className="grid items-center gap-5 sm:grid-cols-[170px_1fr]"><div className="relative mx-auto h-40 w-40 rounded-full" style={{background:`conic-gradient(${stops||"#EEE 0 100%"})`}}><div className="absolute inset-7 grid place-items-center rounded-full bg-white text-center"><div><p className="text-2xl font-semibold">{number(total)}</p><p className="text-[8px] uppercase text-[#211A18]/40">Orders</p></div></div></div><div className="space-y-3">{rows.map((row,i)=><div key={row.status} className="flex items-center justify-between text-[10px]"><span className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{background:colors[i%colors.length]}}/>{row.label}</span><span className="font-semibold">{row.count} <span className="font-normal text-[#211A18]/35">({Number(row.percentage||0).toFixed(1)}%)</span></span></div>)}</div></div>}
