"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Bell, CalendarDays, CalendarClock, ChevronLeft, ChevronRight, Globe2, History, Mail, Play, Save, Trash2, Users } from "lucide-react";
import { confirmAdminAction } from "@/src/components/Admin/AdminConfirmProvider";
import WordBlogEditor from "@/src/components/Admin/WordBlogEditor";
import { uploadBlogImage } from "@/lib/blog";

const API_URL=(process.env.NEXT_PUBLIC_API_URL||"http://localhost:5000").replace(/\/$/,"");
type Audience="all"|"filtered"|"selected";
type Schedule={_id:string;name:string;title:string;subject?:string;message:string;deliveryEmail?:boolean;deliveryWebsite?:boolean;daysBefore?:number[];type:string;link:string;audience:Audience;filters:Record<string,unknown>;userIds:any[];eventType:string;recurrence:string;startDate:string;time:string;timezone:string;nextRunAt:string;lastRunAt?:string;runCount:number;isActive:boolean;createdAt:string};
type Customer={_id:string;name:string;email:string;phone:string;birthday?:string;anniversary?:string};
type HistoryRow={_id:string;ranAt:string;recipientCount:number;status:string;note:string};
type CalendarEvent={id:string;scheduleId:string;scheduleName:string;userName:string;eventType:string;eventDate?:string|null;sendDate:string;daysBefore?:number;channels:string[];status:string};
type Delivery={_id:string;channel:string;status:string;scheduledFor:string;sentAt?:string;failureReason?:string;daysBefore?:number;user?:{name?:string;email?:string};notification?:{title?:string};schedule?:{name?:string;eventType?:string}};
const emptyFilters={accountStatus:"active",search:"",joined:"",lastActive:"",hasCart:"",hasWishlist:"",orderStatus:""};
const initialForm={name:"",title:"",subject:"",message:"",type:"general",link:"",audience:"filtered" as Audience,eventType:"birthday",recurrence:"daily",startDate:new Date().toISOString().slice(0,10),time:"10:00",isActive:true,deliveryEmail:false,deliveryWebsite:true,daysBefore:[0] as number[]};
async function json(r:Response){try{return await r.json()}catch{return {}}}
function monthValue(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}`}

export default function NotificationSchedulesPage(){
 const [form,setForm]=useState(initialForm); const [messageMode,setMessageMode]=useState<"visual"|"html">("visual"); const [filters,setFilters]=useState({...emptyFilters}); const [selectedIds,setSelectedIds]=useState<string[]>([]); const [schedules,setSchedules]=useState<Schedule[]>([]); const [editingId,setEditingId]=useState(""); const [matched,setMatched]=useState(0); const [sample,setSample]=useState<Customer[]>([]); const [customerSearch,setCustomerSearch]=useState(""); const [customerOptions,setCustomerOptions]=useState<Customer[]>([]); const [history,setHistory]=useState<HistoryRow[]>([]); const [historyName,setHistoryName]=useState(""); const [deliveries,setDeliveries]=useState<Delivery[]>([]); const [calendarMonth,setCalendarMonth]=useState(monthValue()); const [calendarEvents,setCalendarEvents]=useState<CalendarEvent[]>([]); const [error,setError]=useState(""); const [success,setSuccess]=useState(""); const [saving,setSaving]=useState(false); const [loading,setLoading]=useState(true);
 const activeFilters=useMemo(()=>Object.entries(filters).filter(([k,v])=>k!=="accountStatus"&&Boolean(v)).length,[filters]);
 async function loadSchedules(){try{setLoading(true);const [sr,dr]=await Promise.all([fetch(`${API_URL}/api/admin/notification-schedules`,{credentials:"include",cache:"no-store"}),fetch(`${API_URL}/api/admin/notification-deliveries?limit=50`,{credentials:"include",cache:"no-store"})]);const sd=await json(sr);const dd=await json(dr);if(!sr.ok)throw new Error(sd?.message||"Unable to load schedules.");setSchedules(Array.isArray(sd?.schedules)?sd.schedules:[]);if(dr.ok)setDeliveries(Array.isArray(dd?.deliveries)?dd.deliveries:[]);}catch(e){setError(e instanceof Error?e.message:"Unable to load schedules.");}finally{setLoading(false)}}
 async function loadCalendar(){try{const r=await fetch(`${API_URL}/api/admin/notification-schedules/calendar?month=${calendarMonth}`,{credentials:"include",cache:"no-store"});const d=await json(r);if(r.ok)setCalendarEvents(Array.isArray(d?.events)?d.events:[]);}catch{}}
 useEffect(()=>{void loadSchedules()},[]); useEffect(()=>{void loadCalendar()},[calendarMonth]);
 useEffect(()=>{const t=window.setTimeout(()=>void preview(),300);return()=>window.clearTimeout(t)},[form.audience,filters,selectedIds]);
 useEffect(()=>{if(form.audience!=="selected"||!customerSearch.trim()){setCustomerOptions([]);return;}const t=window.setTimeout(()=>void(async()=>{const r=await fetch(`${API_URL}/api/admin/customers?limit=12&search=${encodeURIComponent(customerSearch.trim())}`,{credentials:"include",cache:"no-store"});const d=await json(r);if(r.ok)setCustomerOptions(Array.isArray(d?.customers)?d.customers:[]);})(),250);return()=>window.clearTimeout(t)},[customerSearch,form.audience]);
 async function preview(){try{const r=await fetch(`${API_URL}/api/admin/notification-schedules/preview`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({audience:form.audience,filters:form.audience==="filtered"?filters:{},userIds:form.audience==="selected"?selectedIds:[]})});const d=await json(r);if(r.ok){setMatched(Number(d?.count||0));setSample(Array.isArray(d?.customers)?d.customers:[])}}catch{}}
 function reset(){setForm(initialForm);setFilters({...emptyFilters});setSelectedIds([]);setEditingId("");setCustomerSearch("");setHistory([]);setHistoryName("");setMessageMode("visual")}
 function toggleDay(day:number){setForm(f=>({...f,daysBefore:f.daysBefore.includes(day)?f.daysBefore.filter(v=>v!==day):[...f.daysBefore,day].sort((a,b)=>b-a)}))}
 async function save(){try{setSaving(true);setError("");setSuccess("");if(!form.deliveryEmail&&!form.deliveryWebsite)throw new Error("Select Email or Website delivery.");if(form.eventType!=="none"&&!form.daysBefore.length)throw new Error("Select at least one event timing.");const body={...form,subject:form.subject||form.title,filters:form.audience==="filtered"?filters:{},userIds:form.audience==="selected"?selectedIds:[],timezone:"Asia/Kolkata",recurrence:form.eventType==="none"?form.recurrence:"daily"};const r=await fetch(`${API_URL}/api/admin/notification-schedules${editingId?`/${editingId}`:""}`,{method:editingId?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await json(r);if(!r.ok)throw new Error(d?.message||"Unable to save schedule.");setSuccess(editingId?"Schedule updated.":"Schedule created.");reset();await Promise.all([loadSchedules(),loadCalendar()]);}catch(e){setError(e instanceof Error?e.message:"Unable to save schedule.");}finally{setSaving(false)}}
 function edit(s:Schedule){setEditingId(s._id);setForm({name:s.name,title:s.title,subject:s.subject||s.title,message:s.message,type:s.type,link:s.link||"",audience:s.audience,eventType:s.eventType,recurrence:s.recurrence,startDate:s.startDate,time:s.time,isActive:s.isActive,deliveryEmail:Boolean(s.deliveryEmail),deliveryWebsite:s.deliveryWebsite!==false,daysBefore:Array.isArray(s.daysBefore)&&s.daysBefore.length?s.daysBefore:[0]});setFilters({...emptyFilters,...(s.filters||{})} as any);setSelectedIds(Array.isArray(s.userIds)?s.userIds.map((u:any)=>String(u?._id||u)):[]);window.scrollTo({top:0,behavior:"smooth"})}
 async function toggle(s:Schedule){const r=await fetch(`${API_URL}/api/admin/notification-schedules/${s._id}/status`,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({isActive:!s.isActive})});if(r.ok)await loadSchedules()}
 async function remove(s:Schedule){const ok=await confirmAdminAction({title:"Delete notification schedule?",itemName:s.name,description:"Schedule and its run history will be permanently deleted.",confirmLabel:"Delete"});if(!ok)return;const r=await fetch(`${API_URL}/api/admin/notification-schedules/${s._id}`,{method:"DELETE",credentials:"include"});const d=await json(r);if(!r.ok){setError(d?.message||"Delete failed.");return;}await Promise.all([loadSchedules(),loadCalendar()]);if(editingId===s._id)reset()}
 async function runNow(s:Schedule){if(!window.confirm(`Run “${s.name}” now for the currently matching audience? Duplicate deliveries are automatically blocked.`))return;setError("");const r=await fetch(`${API_URL}/api/admin/notification-schedules/${s._id}/run`,{method:"POST",credentials:"include"});const d=await json(r);if(!r.ok){setError(d?.message||"Run failed.");return;}setSuccess(`Run complete: ${d?.result?.recipientCount||0} unique recipient(s), ${d?.result?.emailSent||0} email, ${d?.result?.websiteSent||0} website.`);await Promise.all([showHistory(s),loadSchedules(),loadCalendar()])}
 async function showHistory(s:Schedule){const r=await fetch(`${API_URL}/api/admin/notification-schedules/${s._id}/history`,{credentials:"include",cache:"no-store"});const d=await json(r);if(r.ok){setHistory(Array.isArray(d?.history)?d.history:[]);setHistoryName(s.name)}}
 function moveMonth(delta:number){const [y,m]=calendarMonth.split("-").map(Number);setCalendarMonth(monthValue(new Date(y,m-1+delta,1)))}
 return <div className="min-h-full bg-[#F8F5F2] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1500px]">
  <div className="mb-6"><p className="text-[9px] font-semibold uppercase tracking-[0.22em] text-[#A51D45]">Users · Automation</p><h1 className="mt-2 text-3xl font-semibold">Birthday & Anniversary Notification Schedules</h1><p className="mt-2 text-[11px] text-[#211A18]/50">Email + website delivery, 3/2/1 days before, event-day automation, calendar and delivery history.</p></div>
  {error&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-[11px] text-red-700">{error}</div>}{success&&<div className="mb-4 rounded-xl bg-green-50 p-3 text-[11px] text-green-700">{success}</div>}
  <div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]">
   <section className="rounded-[24px] border border-[#211A18]/10 bg-white p-5 md:p-6"><div className="flex items-center justify-between border-b border-[#211A18]/8 pb-4"><div><h2 className="text-[16px] font-semibold">{editingId?"Edit Schedule":"Add Schedule"}</h2><p className="mt-1 text-[9px] text-[#211A18]/40">Recipients: {matched} users</p></div><CalendarClock size={18} className="text-[#8C1839]"/></div>
    <div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Schedule Name"><input className={input} value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))} placeholder="Birthday greeting"/></Field><Field label="Notification Type"><select className={input} value={form.type} onChange={e=>setForm(f=>({...f,type:e.target.value}))}><option value="general">General</option><option value="promotion">Promotion</option><option value="account">Account</option><option value="system">System</option></select></Field><Field label="Title"><input className={input} value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value,subject:f.subject||e.target.value}))} placeholder="Happy Birthday!"/></Field><Field label="Email Subject"><input className={input} value={form.subject} onChange={e=>setForm(f=>({...f,subject:e.target.value}))} placeholder="Happy Birthday!"/></Field><Field label="Link (Optional)"><input className={input} value={form.link} onChange={e=>setForm(f=>({...f,link:e.target.value}))} placeholder="/offers"/></Field><Field label="Event"><select className={input} value={form.eventType} onChange={e=>setForm(f=>({...f,eventType:e.target.value,recurrence:e.target.value==="none"?f.recurrence:"daily"}))}><option value="birthday">Birthday</option><option value="anniversary">Anniversary</option><option value="none">No Date Event</option></select></Field><Field label="Start Date"><input type="date" className={input} value={form.startDate} onChange={e=>setForm(f=>({...f,startDate:e.target.value}))}/></Field><Field label="Send Time (IST)"><input type="time" className={input} value={form.time} onChange={e=>setForm(f=>({...f,time:e.target.value}))}/></Field>{form.eventType==="none"&&<Field label="Repeat"><select className={input} value={form.recurrence} onChange={e=>setForm(f=>({...f,recurrence:e.target.value}))}><option value="daily">Every Day</option><option value="monthly">Every Month</option><option value="yearly">Every Year</option></select></Field>}</div>
    <div className="mt-5"><p className="mb-2 text-[9px] font-semibold uppercase text-[#211A18]/45">Delivery Channels</p><div className="grid gap-2 sm:grid-cols-2"><button type="button" onClick={()=>setForm(f=>({...f,deliveryEmail:!f.deliveryEmail}))} className={`${toggleBtn} ${form.deliveryEmail?activeToggle:""}`}><Mail size={14}/> Send to Email · {form.deliveryEmail?"ON":"OFF"}</button><button type="button" onClick={()=>setForm(f=>({...f,deliveryWebsite:!f.deliveryWebsite}))} className={`${toggleBtn} ${form.deliveryWebsite?activeToggle:""}`}><Globe2 size={14}/> Send to Website · {form.deliveryWebsite?"ON":"OFF"}</button></div></div>
    {form.eventType!=="none"&&<div className="mt-5"><p className="mb-2 text-[9px] font-semibold uppercase text-[#211A18]/45">Send notification</p><div className="grid gap-2 sm:grid-cols-4">{[[3,"3 days before"],[2,"2 days before"],[1,"1 day before"],[0,"Event day"]].map(([day,label]:any)=><button type="button" key={day} onClick={()=>toggleDay(day)} className={`${toggleBtn} ${form.daysBefore.includes(day)?activeToggle:""}`}>{form.daysBefore.includes(day)?"✓":"○"} {label}</button>)}</div></div>}
    <div className="mt-5"><div className="mb-3 flex items-center justify-between"><p className="text-[9px] font-semibold uppercase text-[#211A18]/45">Message</p><div className="flex gap-2"><button type="button" onClick={()=>setMessageMode("visual")} className={modeBtn(messageMode==="visual")}>Visual Editor</button><button type="button" onClick={()=>setMessageMode("html")} className={modeBtn(messageMode==="html")}>HTML</button></div></div>{messageMode==="visual"?<WordBlogEditor value={form.message} onChange={message=>setForm(f=>({...f,message}))} onImageUpload={uploadBlogImage}/>:<textarea value={form.message} onChange={e=>setForm(f=>({...f,message:e.target.value}))} spellCheck={false} className={`${input} min-h-[420px] resize-y bg-[#171717] py-4 font-mono text-[#F5F5F5]`}/>}<div className="mt-3 rounded-2xl border border-[#211A18]/10 p-3"><p className="mb-2 text-[8px] font-semibold uppercase text-[#211A18]/35">Preview</p><iframe title="Schedule preview" sandbox="" srcDoc={form.message} className="min-h-44 w-full rounded-xl border-0 bg-white"/></div></div>
    <div className="mt-5"><p className="mb-2 text-[10px] font-semibold">Audience</p><div className="grid grid-cols-3 gap-2">{(["all","filtered","selected"] as Audience[]).map(a=><button key={a} type="button" onClick={()=>setForm(f=>({...f,audience:a}))} className={`h-11 rounded-xl border text-[10px] font-semibold ${form.audience===a?"border-[#8C1839]/30 bg-[#FFF3F7] text-[#8C1839]":"border-[#211A18]/10"}`}>{a==="all"?"All Users":a==="filtered"?"Filtered":"Selected"}</button>)}</div></div>
    {form.audience==="filtered"&&<div className="mt-4 grid gap-3 rounded-2xl bg-[#FAF8F6] p-4 sm:grid-cols-2"><FilterField label="Account Status" value={filters.accountStatus} set={(v)=>setFilters(f=>({...f,accountStatus:v}))} options={[["active","Active"],["inactive","Inactive"],["blocked","Blocked"]]}/><Field label="Search"><input className={input} value={filters.search} onChange={e=>setFilters(f=>({...f,search:e.target.value}))} placeholder="Name, email, phone"/></Field><FilterField label="Joined" value={filters.joined} set={(v)=>setFilters(f=>({...f,joined:v}))} options={[["","Any"],["today","Today"],["7d","Last 7 Days"],["30d","Last 30 Days"]]}/><FilterField label="Last Active" value={filters.lastActive} set={(v)=>setFilters(f=>({...f,lastActive:v}))} options={[["","Any"],["today","Today"],["7d","Last 7 Days"],["30plus","30+ Days"]]}/><FilterField label="Cart" value={filters.hasCart} set={(v)=>setFilters(f=>({...f,hasCart:v}))} options={[["","Any"],["true","Has Cart"],["false","Empty Cart"]]}/><FilterField label="Wishlist" value={filters.hasWishlist} set={(v)=>setFilters(f=>({...f,hasWishlist:v}))} options={[["","Any"],["true","Has Wishlist"],["false","Empty Wishlist"]]}/><FilterField label="Orders" value={filters.orderStatus} set={(v)=>setFilters(f=>({...f,orderStatus:v}))} options={[["","Any"],["has","Has Orders"],["never","Never Ordered"]]}/><div className="flex items-end"><button type="button" onClick={()=>setFilters({...emptyFilters})} className="h-12 w-full rounded-xl border border-[#211A18]/10 bg-white text-[9px] font-semibold">Clear {activeFilters} Filters</button></div></div>}
    {form.audience==="selected"&&<div className="mt-4 rounded-2xl bg-[#FAF8F6] p-4"><Field label="Find User"><input className={input} value={customerSearch} onChange={e=>setCustomerSearch(e.target.value)} placeholder="Search customer name/email/phone"/></Field><div className="mt-3 max-h-48 space-y-2 overflow-y-auto">{customerOptions.map(c=><label key={c._id} className="flex items-center gap-3 rounded-xl bg-white p-3 text-[10px]"><input type="checkbox" checked={selectedIds.includes(c._id)} onChange={e=>setSelectedIds(ids=>e.target.checked?[...new Set([...ids,c._id])]:ids.filter(id=>id!==c._id))}/><span><b>{c.name}</b><br/><span className="text-[#211A18]/45">{c.email}</span></span></label>)}</div><p className="mt-3 text-[9px] text-[#211A18]/45">{selectedIds.length} user(s) selected</p></div>}
    {sample.length>0&&<div className="mt-4 rounded-2xl border border-[#211A18]/8 p-4"><p className="mb-2 text-[9px] font-semibold uppercase text-[#211A18]/40">Sample matched users</p>{sample.slice(0,5).map(c=><div key={c._id} className="py-1 text-[10px]"><b>{c.name}</b> · {c.email}</div>)}</div>}
    <label className="mt-5 flex items-center gap-2 text-[10px] font-semibold"><input type="checkbox" checked={form.isActive} onChange={e=>setForm(f=>({...f,isActive:e.target.checked}))} className="accent-[#8C1839]"/>Active schedule</label><div className="mt-5 flex justify-end gap-2">{editingId&&<button onClick={reset} className="h-11 rounded-xl border border-[#211A18]/10 px-4 text-[9px] font-semibold">Cancel</button>}<button disabled={saving||matched===0} onClick={()=>void save()} className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#8C1839] px-5 text-[9px] font-semibold text-white disabled:opacity-50"><Save size={13}/>{saving?"Saving...":editingId?"Update Schedule":"Add Schedule"}</button></div>
   </section>
   <section className="h-fit rounded-[24px] border border-[#211A18]/10 bg-white p-5 md:p-6"><div className="flex items-center justify-between border-b border-[#211A18]/8 pb-4"><div><h2 className="text-[16px] font-semibold">Schedules</h2><p className="mt-1 text-[9px] text-[#211A18]/40">Pause, edit, run now and inspect history.</p></div><Users size={18} className="text-[#8C1839]"/></div>{loading?<p className="py-10 text-center text-[11px] text-[#211A18]/40">Loading...</p>:<div className="mt-4 max-h-[920px] space-y-3 overflow-y-auto pr-1">{schedules.map(s=><div key={s._id} className="rounded-[18px] border border-[#211A18]/8 bg-[#FAF8F6] p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-[12px] font-semibold">{s.name}</h3><span className={`rounded-full px-2 py-1 text-[8px] font-semibold ${s.isActive?"bg-green-100 text-green-700":"bg-red-100 text-red-700"}`}>{s.isActive?"ACTIVE":"PAUSED"}</span></div><p className="mt-1 text-[10px] text-[#211A18]/55">{s.eventType} · {s.time} IST · {s.audience}</p><p className="mt-1 text-[9px] text-[#211A18]/35">{s.deliveryEmail?"Email ":""}{s.deliveryWebsite?"Website":""} · {s.eventType!=="none"?`Before: ${(s.daysBefore||[0]).join(", ")} day(s)`:s.recurrence}</p><p className="mt-1 text-[9px] text-[#211A18]/35">Next: {new Date(s.nextRunAt).toLocaleString("en-IN")} · Runs: {s.runCount||0}</p></div></div><p className="mt-3 text-[10px] font-semibold">{s.title}</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>edit(s)} className={btn}>Edit</button><button onClick={()=>void toggle(s)} className={btn}>{s.isActive?"Pause":"Activate"}</button><button onClick={()=>void runNow(s)} className={btn}><Play size={11}/> Run now</button><button onClick={()=>void showHistory(s)} className={btn}><History size={11}/> History</button><button onClick={()=>void remove(s)} className={`${btn} text-red-600`}><Trash2 size={11}/> Delete</button></div></div>)}{schedules.length===0&&<p className="py-10 text-center text-[11px] text-[#211A18]/40">No schedules yet.</p>}</div>}</section>
  </div>
  <CalendarPanel month={calendarMonth} events={calendarEvents} onPrev={()=>moveMonth(-1)} onNext={()=>moveMonth(1)} onToday={()=>setCalendarMonth(monthValue())}/>
  {historyName&&<section className="mt-5 rounded-[24px] border border-[#211A18]/10 bg-white p-5 md:p-6"><div className="flex items-center justify-between"><div><h2 className="text-[16px] font-semibold">Run History · {historyName}</h2><p className="mt-1 text-[9px] text-[#211A18]/40">Automatic/manual schedule executions.</p></div><button onClick={()=>{setHistoryName("");setHistory([])}} className="text-[9px] font-semibold text-[#8C1839]">Close</button></div><div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-[10px]"><thead className="bg-[#FAF8F6] text-[8px] uppercase text-[#211A18]/40"><tr><th className="px-3 py-2">Run time</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Recipients</th><th className="px-3 py-2">Note</th></tr></thead><tbody>{history.map(h=><tr key={h._id} className="border-t border-[#211A18]/7"><td className="px-3 py-3">{new Date(h.ranAt).toLocaleString("en-IN")}</td><td className="px-3 py-3 uppercase">{h.status}</td><td className="px-3 py-3">{h.recipientCount}</td><td className="px-3 py-3">{h.note}</td></tr>)}</tbody></table>{history.length===0&&<p className="py-6 text-center text-[10px] text-[#211A18]/40">No history yet.</p>}</div></section>}
  <section className="mt-5 rounded-[24px] border border-[#211A18]/10 bg-white p-5 md:p-6"><div className="flex items-center gap-3"><Bell size={18} className="text-[#8C1839]"/><div><h2 className="text-[16px] font-semibold">Notification Delivery History</h2><p className="mt-1 text-[9px] text-[#211A18]/40">Per-recipient Email / Website status and failure reason.</p></div></div><div className="mt-4 overflow-auto"><table className="w-full min-w-[900px] text-left text-[10px]"><thead className="bg-[#FAF8F6] text-[8px] uppercase text-[#211A18]/40"><tr><th className="px-3 py-3">Notification</th><th className="px-3 py-3">Recipient</th><th className="px-3 py-3">Channel</th><th className="px-3 py-3">Scheduled</th><th className="px-3 py-3">Sent</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Error</th></tr></thead><tbody>{deliveries.map(d=><tr key={d._id} className="border-t border-[#211A18]/7"><td className="px-3 py-3 font-semibold">{d.notification?.title||d.schedule?.name||"Notification"}</td><td className="px-3 py-3">{d.user?.name||"Customer"}<br/><span className="text-[#211A18]/35">{d.user?.email}</span></td><td className="px-3 py-3 uppercase">{d.channel}</td><td className="px-3 py-3">{new Date(d.scheduledFor).toLocaleString("en-IN")}</td><td className="px-3 py-3">{d.sentAt?new Date(d.sentAt).toLocaleString("en-IN"):"—"}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-[8px] font-semibold uppercase ${d.status==="sent"?"bg-green-100 text-green-700":d.status==="failed"?"bg-red-100 text-red-700":"bg-amber-100 text-amber-700"}`}>{d.status}</span></td><td className="max-w-[260px] px-3 py-3 text-red-600">{d.failureReason||"—"}</td></tr>)}</tbody></table>{!deliveries.length&&<p className="py-8 text-center text-[10px] text-[#211A18]/40">No delivery history yet.</p>}</div></section>
 </div></div>
}

function CalendarPanel({month,events,onPrev,onNext,onToday}:{month:string;events:CalendarEvent[];onPrev:()=>void;onNext:()=>void;onToday:()=>void}){const [y,m]=month.split("-").map(Number);const first=new Date(y,m-1,1);const days=new Date(y,m,0).getDate();const offset=(first.getDay()+6)%7;const cells=Array.from({length:offset+days},(_,i)=>i<offset?null:i-offset+1);const byDay=new Map<number,CalendarEvent[]>();events.forEach(e=>{const d=new Date(e.sendDate);if(d.getFullYear()===y&&d.getMonth()===m-1){const list=byDay.get(d.getDate())||[];list.push(e);byDay.set(d.getDate(),list)}});return <section className="mt-5 rounded-[24px] border border-[#211A18]/10 bg-white p-5 md:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><CalendarDays size={18} className="text-[#8C1839]"/><div><h2 className="text-[16px] font-semibold">Automation Calendar</h2><p className="mt-1 text-[9px] text-[#211A18]/40">Birthday, anniversary and scheduled notification send dates.</p></div></div><div className="flex items-center gap-2"><button onClick={onPrev} className={navBtn}><ChevronLeft size={14}/></button><button onClick={onToday} className={`${navBtn} px-4`}>Today</button><button onClick={onNext} className={navBtn}><ChevronRight size={14}/></button><span className="ml-2 text-[12px] font-semibold">{first.toLocaleDateString("en-IN",{month:"long",year:"numeric"})}</span></div></div><div className="mt-5 grid grid-cols-7 text-center text-[8px] font-semibold uppercase text-[#211A18]/35">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(d=><div key={d} className="py-2">{d}</div>)}</div><div className="grid grid-cols-7 overflow-hidden rounded-2xl border border-[#211A18]/8">{cells.map((day,i)=><div key={i} className="min-h-[115px] border-b border-r border-[#211A18]/7 p-2 last:border-r-0">{day&&<><p className="text-[9px] font-semibold text-[#211A18]/45">{day}</p><div className="mt-2 space-y-1">{(byDay.get(day)||[]).slice(0,3).map(e=><div key={e.id} title={`${e.userName} · ${e.scheduleName}`} className={`rounded-lg px-2 py-1.5 text-[8px] leading-3 ${e.eventType==="birthday"?"bg-[#FFF0F5] text-[#8C1839]":e.eventType==="anniversary"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}><b>{e.userName}</b><br/>{e.eventType} · {e.daysBefore?`${e.daysBefore}d before`:"day"}<br/>{e.channels.join(" + ")}</div>)}{(byDay.get(day)||[]).length>3&&<p className="text-[8px] text-[#211A18]/35">+{(byDay.get(day)||[]).length-3} more</p>}</div></>}</div>)}</div>{events.length===0&&<p className="py-8 text-center text-[10px] text-[#211A18]/40">No automation events for this month.</p>}</section>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block"><span className="mb-2 block text-[9px] font-semibold uppercase tracking-[0.06em] text-[#211A18]/45">{label}</span>{children}</label>}
function FilterField({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:[string,string][]}){return <Field label={label}><select className={input} value={value} onChange={e=>set(e.target.value)}>{options.map(([v,l])=><option key={`${label}-${v}`} value={v}>{l}</option>)}</select></Field>}
const input="min-h-12 w-full rounded-[14px] border border-[#211A18]/10 bg-[#FAF8F6] px-4 text-[11px] outline-none focus:border-[#8C1839]/30";
const btn="inline-flex h-9 items-center gap-1.5 rounded-lg border border-[#211A18]/10 bg-white px-3 text-[8px] font-semibold";
const toggleBtn="flex min-h-11 items-center justify-center gap-2 rounded-xl border border-[#211A18]/10 bg-white px-3 text-[9px] font-semibold";
const activeToggle="!border-[#8C1839]/30 !bg-[#FFF3F7] !text-[#8C1839]";
const navBtn="inline-flex h-9 min-w-9 items-center justify-center rounded-lg border border-[#211A18]/10 bg-white text-[9px] font-semibold";
function modeBtn(active:boolean){return `h-9 rounded-lg px-3 text-[9px] font-semibold ${active?"bg-[#8C1839] text-white":"bg-[#FAF8F6] text-[#211A18]/60"}`}
