"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import { CalendarClock, History, Play, Save, Trash2, Users } from "lucide-react";
import { confirmAdminAction } from "@/src/components/Admin/AdminConfirmProvider";

const API_URL=(process.env.NEXT_PUBLIC_API_URL||"http://localhost:5000").replace(/\/$/,"");
type Audience="all"|"filtered"|"selected";
type Schedule={_id:string;name:string;title:string;message:string;type:string;link:string;audience:Audience;filters:Record<string,unknown>;userIds:any[];eventType:string;recurrence:string;startDate:string;time:string;timezone:string;nextRunAt:string;lastRunAt?:string;runCount:number;isActive:boolean;createdAt:string};
type Customer={_id:string;name:string;email:string;phone:string;birthday?:string;anniversary?:string};
type HistoryRow={_id:string;ranAt:string;recipientCount:number;status:string;note:string};
const emptyFilters={accountStatus:"active",search:"",joined:"",lastActive:"",hasCart:"",hasWishlist:"",orderStatus:""};
const initialForm={name:"",title:"",message:"",type:"general",link:"",audience:"filtered" as Audience,eventType:"birthday",recurrence:"daily",startDate:new Date().toISOString().slice(0,10),time:"10:00",isActive:true};
async function json(r:Response){try{return await r.json()}catch{return {}}}

export default function NotificationSchedulesPage(){
 const [form,setForm]=useState(initialForm); const [filters,setFilters]=useState({...emptyFilters}); const [selectedIds,setSelectedIds]=useState<string[]>([]); const [schedules,setSchedules]=useState<Schedule[]>([]); const [editingId,setEditingId]=useState(""); const [matched,setMatched]=useState(0); const [sample,setSample]=useState<Customer[]>([]); const [customerSearch,setCustomerSearch]=useState(""); const [customerOptions,setCustomerOptions]=useState<Customer[]>([]); const [history,setHistory]=useState<HistoryRow[]>([]); const [historyName,setHistoryName]=useState(""); const [error,setError]=useState(""); const [success,setSuccess]=useState(""); const [saving,setSaving]=useState(false); const [loading,setLoading]=useState(true);
 const activeFilters=useMemo(()=>Object.values(filters).filter(Boolean).length,[filters]);
 async function loadSchedules(){try{setLoading(true);const r=await fetch(`${API_URL}/api/admin/notification-schedules`,{credentials:"include",cache:"no-store"});const d=await json(r);if(!r.ok)throw new Error(d?.message||"Unable to load schedules.");setSchedules(Array.isArray(d?.schedules)?d.schedules:[]);}catch(e){setError(e instanceof Error?e.message:"Unable to load schedules.");}finally{setLoading(false)}}
 useEffect(()=>{void loadSchedules()},[]);
 useEffect(()=>{const t=window.setTimeout(()=>void preview(),300);return()=>window.clearTimeout(t)},[form.audience,filters,selectedIds]);
 useEffect(()=>{if(form.audience!=="selected"||!customerSearch.trim()){setCustomerOptions([]);return;}const t=window.setTimeout(()=>void(async()=>{const r=await fetch(`${API_URL}/api/admin/customers?limit=10&search=${encodeURIComponent(customerSearch.trim())}`,{credentials:"include",cache:"no-store"});const d=await json(r);if(r.ok)setCustomerOptions(Array.isArray(d?.customers)?d.customers:[]);})(),250);return()=>window.clearTimeout(t)},[customerSearch,form.audience]);
 async function preview(){try{const r=await fetch(`${API_URL}/api/admin/notification-schedules/preview`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({audience:form.audience,filters:form.audience==="filtered"?filters:{},userIds:form.audience==="selected"?selectedIds:[]})});const d=await json(r);if(r.ok){setMatched(Number(d?.count||0));setSample(Array.isArray(d?.customers)?d.customers:[])}}catch{}}
 function reset(){setForm(initialForm);setFilters({...emptyFilters});setSelectedIds([]);setEditingId("");setCustomerSearch("");setHistory([]);setHistoryName("");}
 async function save(){try{setSaving(true);setError("");setSuccess("");const body={...form,filters:form.audience==="filtered"?filters:{},userIds:form.audience==="selected"?selectedIds:[],timezone:"Asia/Kolkata"};const r=await fetch(`${API_URL}/api/admin/notification-schedules${editingId?`/${editingId}`:""}`,{method:editingId?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await json(r);if(!r.ok)throw new Error(d?.message||"Unable to save schedule.");setSuccess(editingId?"Schedule updated.":"Schedule created.");reset();await loadSchedules();}catch(e){setError(e instanceof Error?e.message:"Unable to save schedule.");}finally{setSaving(false)}}
 function edit(s:Schedule){setEditingId(s._id);setForm({name:s.name,title:s.title,message:s.message,type:s.type,link:s.link||"",audience:s.audience,eventType:s.eventType,recurrence:s.recurrence,startDate:s.startDate,time:s.time,isActive:s.isActive});setFilters({...emptyFilters,...(s.filters||{})} as any);setSelectedIds(Array.isArray(s.userIds)?s.userIds.map((u:any)=>String(u?._id||u)):[]);window.scrollTo({top:0,behavior:"smooth"})}
 async function toggle(s:Schedule){const r=await fetch(`${API_URL}/api/admin/notification-schedules/${s._id}/status`,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({isActive:!s.isActive})});if(r.ok)await loadSchedules()}
 async function remove(s:Schedule){const ok=await confirmAdminAction({title:"Delete notification schedule?",itemName:s.name,description:"Schedule and its run history will be permanently deleted.",confirmLabel:"Delete"});if(!ok)return;const r=await fetch(`${API_URL}/api/admin/notification-schedules/${s._id}`,{method:"DELETE",credentials:"include"});const d=await json(r);if(!r.ok){setError(d?.message||"Delete failed.");return;}await loadSchedules();if(editingId===s._id)reset()}
 async function runNow(s:Schedule){setError("");const r=await fetch(`${API_URL}/api/admin/notification-schedules/${s._id}/run`,{method:"POST",credentials:"include"});const d=await json(r);if(!r.ok){setError(d?.message||"Run failed.");return;}setSuccess(`Schedule run complete: ${d?.result?.recipientCount||0} recipient(s).`);await showHistory(s)}
 async function showHistory(s:Schedule){const r=await fetch(`${API_URL}/api/admin/notification-schedules/${s._id}/history`,{credentials:"include",cache:"no-store"});const d=await json(r);if(r.ok){setHistory(Array.isArray(d?.history)?d.history:[]);setHistoryName(s.name)}}
 return <div className="min-h-full bg-[#F8F5F2] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1500px]">
  <div className="mb-6"><p className="text-[9px] font-semibold uppercase tracking-[0.22em] text-[#A51D45]">Users · Automation</p><h1 className="mt-2 text-3xl font-semibold">Birthday & Anniversary Notification Schedules</h1><p className="mt-2 text-[11px] text-[#211A18]/50">Filter users first, choose birthday/anniversary, set schedule time and repeat daily, monthly or yearly.</p></div>
  {error&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-[11px] text-red-700">{error}</div>}{success&&<div className="mb-4 rounded-xl bg-green-50 p-3 text-[11px] text-green-700">{success}</div>}
  <div className="grid gap-5 xl:grid-cols-[1.05fr_.95fr]">
   <section className="rounded-[24px] border border-[#211A18]/10 bg-white p-5 md:p-6"><div className="flex items-center justify-between border-b border-[#211A18]/8 pb-4"><div><h2 className="text-[16px] font-semibold">{editingId?"Edit Schedule":"Add Schedule"}</h2><p className="mt-1 text-[9px] text-[#211A18]/40">Matched users: {matched}</p></div><CalendarClock size={18} className="text-[#8C1839]"/></div>
    <div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Schedule Name"><input className={input} value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))} placeholder="Birthday greeting"/></Field><Field label="Notification Type"><select className={input} value={form.type} onChange={e=>setForm(f=>({...f,type:e.target.value}))}><option value="general">General</option><option value="promotion">Promotion</option><option value="account">Account</option><option value="system">System</option></select></Field><Field label="Title"><input className={input} value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))} placeholder="Happy Birthday!"/></Field><Field label="Link (Optional)"><input className={input} value={form.link} onChange={e=>setForm(f=>({...f,link:e.target.value}))} placeholder="/offers"/></Field><Field label="Message"><textarea className={`${input} min-h-[110px] py-3`} value={form.message} onChange={e=>setForm(f=>({...f,message:e.target.value}))}/></Field><div className="grid gap-4"><Field label="Event"><select className={input} value={form.eventType} onChange={e=>setForm(f=>({...f,eventType:e.target.value}))}><option value="birthday">Birthday</option><option value="anniversary">Anniversary</option><option value="none">No Date Event</option></select></Field><Field label="Repeat"><select className={input} value={form.recurrence} onChange={e=>setForm(f=>({...f,recurrence:e.target.value}))}><option value="daily">Every Day</option><option value="monthly">Every Month</option><option value="yearly">Every Year</option></select></Field></div><Field label="Start Date"><input type="date" className={input} value={form.startDate} onChange={e=>setForm(f=>({...f,startDate:e.target.value}))}/></Field><Field label="Send Time (IST)"><input type="time" className={input} value={form.time} onChange={e=>setForm(f=>({...f,time:e.target.value}))}/></Field></div>
    <div className="mt-5"><p className="mb-2 text-[10px] font-semibold">Audience</p><div className="grid grid-cols-3 gap-2">{(["all","filtered","selected"] as Audience[]).map(a=><button key={a} type="button" onClick={()=>setForm(f=>({...f,audience:a}))} className={`h-11 rounded-xl border text-[10px] font-semibold ${form.audience===a?"border-[#8C1839]/30 bg-[#FFF3F7] text-[#8C1839]":"border-[#211A18]/10"}`}>{a==="all"?"All Users":a==="filtered"?"Filtered":"Selected"}</button>)}</div></div>
    {form.audience==="filtered"&&<div className="mt-4 grid gap-3 rounded-2xl bg-[#FAF8F6] p-4 sm:grid-cols-2"><Filter label="Account Status" value={filters.accountStatus} set={(v)=>setFilters(f=>({...f,accountStatus:v}))} options={[["active","Active"],["inactive","Inactive"],["blocked","Blocked"]]}/><Field label="Search"><input className={input} value={filters.search} onChange={e=>setFilters(f=>({...f,search:e.target.value}))} placeholder="Name, email, phone"/></Field><Filter label="Joined" value={filters.joined} set={(v)=>setFilters(f=>({...f,joined:v}))} options={[["","Any"],["today","Today"],["7d","Last 7 Days"],["30d","Last 30 Days"]]}/><Filter label="Last Active" value={filters.lastActive} set={(v)=>setFilters(f=>({...f,lastActive:v}))} options={[["","Any"],["today","Today"],["7d","Last 7 Days"],["30plus","30+ Days"]]}/><Filter label="Cart" value={filters.hasCart} set={(v)=>setFilters(f=>({...f,hasCart:v}))} options={[["","Any"],["true","Has Cart"],["false","Empty Cart"]]}/><Filter label="Wishlist" value={filters.hasWishlist} set={(v)=>setFilters(f=>({...f,hasWishlist:v}))} options={[["","Any"],["true","Has Wishlist"],["false","Empty Wishlist"]]}/><Filter label="Orders" value={filters.orderStatus} set={(v)=>setFilters(f=>({...f,orderStatus:v}))} options={[["","Any"],["has","Has Orders"],["never","Never Ordered"]]}/><div className="flex items-end"><button type="button" onClick={()=>setFilters({...emptyFilters})} className="h-12 w-full rounded-xl border border-[#211A18]/10 bg-white text-[9px] font-semibold">Clear {activeFilters} Filters</button></div></div>}
    {form.audience==="selected"&&<div className="mt-4 rounded-2xl bg-[#FAF8F6] p-4"><Field label="Find User"><input className={input} value={customerSearch} onChange={e=>setCustomerSearch(e.target.value)} placeholder="Search customer name/email/phone"/></Field><div className="mt-3 max-h-48 space-y-2 overflow-y-auto">{customerOptions.map(c=><label key={c._id} className="flex items-center gap-3 rounded-xl bg-white p-3 text-[10px]"><input type="checkbox" checked={selectedIds.includes(c._id)} onChange={e=>setSelectedIds(ids=>e.target.checked?[...new Set([...ids,c._id])]:ids.filter(id=>id!==c._id))}/><span><b>{c.name}</b><br/><span className="text-[#211A18]/45">{c.email}</span></span></label>)}</div><p className="mt-3 text-[9px] text-[#211A18]/45">{selectedIds.length} user(s) selected</p></div>}
    {sample.length>0&&<div className="mt-4 rounded-2xl border border-[#211A18]/8 p-4"><p className="mb-2 text-[9px] font-semibold uppercase text-[#211A18]/40">Sample matched users</p>{sample.slice(0,5).map(c=><div key={c._id} className="py-1 text-[10px]"><b>{c.name}</b> · {c.email}</div>)}</div>}
    <label className="mt-5 flex items-center gap-2 text-[10px] font-semibold"><input type="checkbox" checked={form.isActive} onChange={e=>setForm(f=>({...f,isActive:e.target.checked}))} className="accent-[#8C1839]"/>Active schedule</label><div className="mt-5 flex justify-end gap-2">{editingId&&<button onClick={reset} className="h-11 rounded-xl border border-[#211A18]/10 px-4 text-[9px] font-semibold">Cancel</button>}<button disabled={saving} onClick={()=>void save()} className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#8C1839] px-5 text-[9px] font-semibold text-white disabled:opacity-50"><Save size={13}/>{saving?"Saving...":editingId?"Update Schedule":"Add Schedule"}</button></div>
   </section>
   <section className="rounded-[24px] border border-[#211A18]/10 bg-white p-5 md:p-6"><div className="flex items-center justify-between border-b border-[#211A18]/8 pb-4"><div><h2 className="text-[16px] font-semibold">Schedules</h2><p className="mt-1 text-[9px] text-[#211A18]/40">Active / pause, edit, run and history.</p></div><Users size={18} className="text-[#8C1839]"/></div>{loading?<p className="py-10 text-center text-[11px] text-[#211A18]/40">Loading...</p>:<div className="mt-4 space-y-3">{schedules.map(s=><div key={s._id} className="rounded-[18px] border border-[#211A18]/8 bg-[#FAF8F6] p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-[12px] font-semibold">{s.name}</h3><span className={`rounded-full px-2 py-1 text-[8px] font-semibold ${s.isActive?"bg-green-100 text-green-700":"bg-red-100 text-red-700"}`}>{s.isActive?"ACTIVE":"PAUSED"}</span></div><p className="mt-1 text-[10px] text-[#211A18]/55">{s.eventType} · {s.recurrence} · {s.time} IST · {s.audience}</p><p className="mt-1 text-[9px] text-[#211A18]/35">Next: {new Date(s.nextRunAt).toLocaleString("en-IN")} · Runs: {s.runCount||0}</p></div></div><p className="mt-3 text-[10px] font-semibold">{s.title}</p><p className="mt-1 line-clamp-2 text-[9px] leading-4 text-[#211A18]/50">{s.message}</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>edit(s)} className={btn}>Edit</button><button onClick={()=>void toggle(s)} className={btn}>{s.isActive?"Pause":"Activate"}</button><button onClick={()=>void runNow(s)} className={btn}><Play size={11}/> Run now</button><button onClick={()=>void showHistory(s)} className={btn}><History size={11}/> History</button><button onClick={()=>void remove(s)} className={`${btn} text-red-600`}><Trash2 size={11}/> Delete</button></div></div>)}{schedules.length===0&&<p className="py-10 text-center text-[11px] text-[#211A18]/40">No schedules yet.</p>}</div>}</section>
  </div>
  {historyName&&<section className="mt-5 rounded-[24px] border border-[#211A18]/10 bg-white p-5 md:p-6"><div className="flex items-center justify-between"><div><h2 className="text-[16px] font-semibold">History · {historyName}</h2><p className="mt-1 text-[9px] text-[#211A18]/40">Every automatic/manual run is recorded.</p></div><button onClick={()=>{setHistoryName("");setHistory([])}} className="text-[9px] font-semibold text-[#8C1839]">Close</button></div><div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-[10px]"><thead className="bg-[#FAF8F6] text-[8px] uppercase text-[#211A18]/40"><tr><th className="px-3 py-2">Run time</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Recipients</th><th className="px-3 py-2">Note</th></tr></thead><tbody>{history.map(h=><tr key={h._id} className="border-t border-[#211A18]/7"><td className="px-3 py-3">{new Date(h.ranAt).toLocaleString("en-IN")}</td><td className="px-3 py-3 uppercase">{h.status}</td><td className="px-3 py-3">{h.recipientCount}</td><td className="px-3 py-3">{h.note}</td></tr>)}</tbody></table>{history.length===0&&<p className="py-6 text-center text-[10px] text-[#211A18]/40">No history yet.</p>}</div></section>}
 </div></div>
}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block"><span className="mb-2 block text-[9px] font-semibold uppercase tracking-[0.06em] text-[#211A18]/45">{label}</span>{children}</label>}
function Filter({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:[string,string][]}){return <Field label={label}><select className={input} value={value} onChange={e=>set(e.target.value)}>{options.map(([v,l])=><option key={`${label}-${v}`} value={v}>{l}</option>)}</select></Field>}
const input="min-h-12 w-full rounded-[14px] border border-[#211A18]/10 bg-[#FAF8F6] px-4 text-[11px] outline-none focus:border-[#8C1839]/30";
const btn="inline-flex h-9 items-center gap-1.5 rounded-lg border border-[#211A18]/10 bg-white px-3 text-[8px] font-semibold";
