"use client";

import { useState, type FormEvent, type ReactNode } from "react";
import Header from "@/src/components/Header/Header";

const API_URL=(process.env.NEXT_PUBLIC_API_URL||"http://localhost:5000").replace(/\/$/,"");
const initial={fullName:"",mobileNumber:"",emailAddress:"",city:"",sellingPlatform:"",expectedOrderQuantity:""};

export default function ResellerRegistrationPage(){
 const [form,setForm]=useState(initial);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
 async function submit(e:FormEvent){e.preventDefault();try{setSaving(true);setMessage("");setError("");const r=await fetch(`${API_URL}/api/reseller-registration`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||"Unable to submit.");setMessage("Reseller registration submitted successfully.");setForm(initial);}catch(err){setError(err instanceof Error?err.message:"Unable to submit.");}finally{setSaving(false)}}
 return <><Header/><main className="min-h-screen bg-[#F8F5F2] px-4 py-10 md:py-16"><div className="mx-auto max-w-[900px]"><div className="text-center"><p className="text-[10px] font-semibold uppercase tracking-[0.24em] text-[#A51D45]">Hivra Soft Partner Program</p><h1 className="mt-3 font-serif text-4xl md:text-5xl">Reseller Registration</h1><p className="mx-auto mt-4 max-w-2xl text-[13px] leading-6 text-[#211A18]/55">Register your details and our team can connect with you for reseller pricing and support.</p></div>{message&&<div className="mt-6 rounded-xl bg-green-50 p-4 text-[12px] text-green-700">{message}</div>}{error&&<div className="mt-6 rounded-xl bg-red-50 p-4 text-[12px] text-red-700">{error}</div>}<form onSubmit={submit} className="mt-8 grid gap-5 rounded-[28px] border border-[#211A18]/10 bg-white p-6 md:grid-cols-2 md:p-8"><Field label="Pura Naam *"><input required className={input} value={form.fullName} onChange={e=>setForm(f=>({...f,fullName:e.target.value}))}/></Field><Field label="Mobile Number *"><input required className={input} value={form.mobileNumber} onChange={e=>setForm(f=>({...f,mobileNumber:e.target.value}))}/></Field><Field label="Email Address *"><input type="email" required className={input} value={form.emailAddress} onChange={e=>setForm(f=>({...f,emailAddress:e.target.value}))}/></Field><Field label="City / Shehar *"><input required className={input} value={form.city} onChange={e=>setForm(f=>({...f,city:e.target.value}))}/></Field><Field label="Selling Platform *"><select required className={input} value={form.sellingPlatform} onChange={e=>setForm(f=>({...f,sellingPlatform:e.target.value}))}><option value="">Choose platform</option><option value="whatsapp_instagram">WhatsApp / Instagram</option><option value="meesho_glowroad">Meesho / GlowRoad</option><option value="online_store">Apna Online Store</option><option value="offline_local_market">Offline / Local Market</option><option value="multiple_platforms">Multiple Platforms</option></select></Field><Field label="Expected Order Quantity *"><select required className={input} value={form.expectedOrderQuantity} onChange={e=>setForm(f=>({...f,expectedOrderQuantity:e.target.value}))}><option value="">Choose quantity</option><option value="20_49">20-49 pieces (15% off)</option><option value="50_99">50-99 pieces (20% off)</option><option value="100_199">100-199 pieces (30% off)</option><option value="200_plus">200+ pieces</option></select></Field><div className="md:col-span-2 flex justify-end"><button disabled={saving} className="h-12 rounded-xl bg-[#8C1839] px-7 text-[11px] font-semibold text-white disabled:opacity-50">{saving?"Submitting...":"Register"}</button></div></form></div></main></>
}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block"><span className="mb-2 block text-[11px] font-semibold">{label}</span>{children}</label>}
const input="h-12 w-full rounded-xl border border-[#211A18]/10 bg-[#FAF8F6] px-4 text-[12px] outline-none focus:border-[#8C1839]/40";
